[2023-10-03T10:03:35.110+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T10:03:35.237+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T10:03:35.238+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:03:35.553+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-30 00:00:00+00:00
[2023-10-03T10:03:35.697+0000] {standard_task_runner.py:57} INFO - Started process 1666 to run task
[2023-10-03T10:03:35.720+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'preprocess_data', 'scheduled__2023-09-30T00:00:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmppazmrtsb']
[2023-10-03T10:03:35.760+0000] {standard_task_runner.py:85} INFO - Job 148: Subtask preprocess_data
[2023-10-03T10:03:36.793+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T10:03:38.390+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-30T00:00:00+00:00'
[2023-10-03T10:03:38.499+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 63, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T10:03:38.540+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=preprocess_data, execution_date=20230930T000000, start_date=20231003T100335, end_date=20231003T100338
[2023-10-03T10:03:38.712+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 148 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 1666)
[2023-10-03T10:03:38.849+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:03:38.973+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T12:33:28.925+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T12:33:28.949+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T12:33:28.950+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T12:33:29.264+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-30 00:00:00+00:00
[2023-10-03T12:33:29.431+0000] {standard_task_runner.py:57} INFO - Started process 105 to run task
[2023-10-03T12:33:29.508+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'preprocess_data', 'scheduled__2023-09-30T00:00:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmpx_cj1irv']
[2023-10-03T12:33:29.543+0000] {standard_task_runner.py:85} INFO - Job 231: Subtask preprocess_data
[2023-10-03T12:33:30.840+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T12:33:32.826+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-30T00:00:00+00:00'
[2023-10-03T12:33:33.029+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 75, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T12:33:33.166+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=preprocess_data, execution_date=20230930T000000, start_date=20231003T123328, end_date=20231003T123333
[2023-10-03T12:33:33.392+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 231 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 105)
[2023-10-03T12:33:33.561+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T12:33:33.724+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T12:56:58.195+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T12:56:58.415+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T12:56:58.424+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T12:56:58.749+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-30 00:00:00+00:00
[2023-10-03T12:56:58.823+0000] {standard_task_runner.py:57} INFO - Started process 121 to run task
[2023-10-03T12:56:58.855+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'preprocess_data', 'scheduled__2023-09-30T00:00:00+00:00', '--job-id', '294', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmpwtio4qx0']
[2023-10-03T12:56:58.866+0000] {standard_task_runner.py:85} INFO - Job 294: Subtask preprocess_data
[2023-10-03T12:56:59.391+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T12:57:01.158+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-30T00:00:00+00:00'
[2023-10-03T12:57:01.343+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 75, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T12:57:01.480+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=preprocess_data, execution_date=20230930T000000, start_date=20231003T125658, end_date=20231003T125701
[2023-10-03T12:57:02.316+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 294 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 121)
[2023-10-03T12:57:02.587+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T12:57:03.101+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
