[2023-10-03T10:03:49.706+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03T10:03:49.762+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03T10:03:49.764+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:03:49.996+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-10-02 00:00:00+00:00
[2023-10-03T10:03:50.049+0000] {standard_task_runner.py:57} INFO - Started process 1682 to run task
[2023-10-03T10:03:50.096+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'preprocess_data', 'scheduled__2023-10-02T00:00:00+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmp2p8ug4_4']
[2023-10-03T10:03:50.099+0000] {standard_task_runner.py:85} INFO - Job 152: Subtask preprocess_data
[2023-10-03T10:03:50.417+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.preprocess_data scheduled__2023-10-02T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T10:03:52.711+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-02T00:00:00+00:00'
[2023-10-03T10:03:52.761+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 63, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T10:03:52.804+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=preprocess_data, execution_date=20231002T000000, start_date=20231003T100349, end_date=20231003T100352
[2023-10-03T10:03:53.016+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 152 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 1682)
[2023-10-03T10:03:53.227+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:03:53.312+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T12:37:44.246+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03T12:37:44.528+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03T12:37:44.560+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T12:37:44.894+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-10-02 00:00:00+00:00
[2023-10-03T12:37:45.007+0000] {standard_task_runner.py:57} INFO - Started process 81 to run task
[2023-10-03T12:37:45.027+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'preprocess_data', 'scheduled__2023-10-02T00:00:00+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmp68hpm87_']
[2023-10-03T12:37:45.100+0000] {standard_task_runner.py:85} INFO - Job 238: Subtask preprocess_data
[2023-10-03T12:37:46.122+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.preprocess_data scheduled__2023-10-02T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T12:37:47.284+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-02T00:00:00+00:00'
[2023-10-03T12:37:47.360+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 75, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T12:37:47.461+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=preprocess_data, execution_date=20231002T000000, start_date=20231003T123744, end_date=20231003T123747
[2023-10-03T12:37:47.566+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 238 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 81)
[2023-10-03T12:37:47.641+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T12:37:47.721+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T12:57:27.561+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03T12:57:27.733+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03T12:57:27.746+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T12:57:28.036+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-10-02 00:00:00+00:00
[2023-10-03T12:57:28.169+0000] {standard_task_runner.py:57} INFO - Started process 165 to run task
[2023-10-03T12:57:28.243+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'preprocess_data', 'scheduled__2023-10-02T00:00:00+00:00', '--job-id', '308', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmp53po2nqo']
[2023-10-03T12:57:28.337+0000] {standard_task_runner.py:85} INFO - Job 308: Subtask preprocess_data
[2023-10-03T12:57:28.885+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.preprocess_data scheduled__2023-10-02T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T12:57:30.162+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-02T00:00:00+00:00'
[2023-10-03T12:57:30.350+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 75, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T12:57:30.535+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=preprocess_data, execution_date=20231002T000000, start_date=20231003T125727, end_date=20231003T125730
[2023-10-03T12:57:31.038+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 308 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 165)
[2023-10-03T12:57:31.289+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T12:57:31.541+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
