[2023-10-03T10:03:34.984+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-23T00:00:00+00:00 [queued]>
[2023-10-03T10:03:35.119+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-23T00:00:00+00:00 [queued]>
[2023-10-03T10:03:35.120+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:03:35.421+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-23 00:00:00+00:00
[2023-10-03T10:03:35.591+0000] {standard_task_runner.py:57} INFO - Started process 1665 to run task
[2023-10-03T10:03:35.666+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'preprocess_data', 'scheduled__2023-09-23T00:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmpba6rffck']
[2023-10-03T10:03:35.731+0000] {standard_task_runner.py:85} INFO - Job 146: Subtask preprocess_data
[2023-10-03T10:03:36.631+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.preprocess_data scheduled__2023-09-23T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T10:03:38.039+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-23T00:00:00+00:00'
[2023-10-03T10:03:38.222+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 63, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T10:03:38.327+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=preprocess_data, execution_date=20230923T000000, start_date=20231003T100334, end_date=20231003T100338
[2023-10-03T10:03:38.479+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 146 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 1665)
[2023-10-03T10:03:38.597+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:03:38.656+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T12:33:28.206+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-23T00:00:00+00:00 [queued]>
[2023-10-03T12:33:28.457+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-23T00:00:00+00:00 [queued]>
[2023-10-03T12:33:28.485+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T12:33:29.211+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-23 00:00:00+00:00
[2023-10-03T12:33:29.443+0000] {standard_task_runner.py:57} INFO - Started process 106 to run task
[2023-10-03T12:33:29.476+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'preprocess_data', 'scheduled__2023-09-23T00:00:00+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmp4ww2i3sj']
[2023-10-03T12:33:29.503+0000] {standard_task_runner.py:85} INFO - Job 220: Subtask preprocess_data
[2023-10-03T12:33:30.442+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.preprocess_data scheduled__2023-09-23T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T12:33:32.565+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-23T00:00:00+00:00'
[2023-10-03T12:33:32.794+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 75, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T12:33:32.881+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=preprocess_data, execution_date=20230923T000000, start_date=20231003T123328, end_date=20231003T123332
[2023-10-03T12:33:33.129+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 220 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 106)
[2023-10-03T12:33:33.397+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T12:33:33.639+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T12:56:57.901+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-23T00:00:00+00:00 [queued]>
[2023-10-03T12:56:57.943+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-23T00:00:00+00:00 [queued]>
[2023-10-03T12:56:57.944+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T12:56:58.080+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-23 00:00:00+00:00
[2023-10-03T12:56:58.177+0000] {standard_task_runner.py:57} INFO - Started process 111 to run task
[2023-10-03T12:56:58.258+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'preprocess_data', 'scheduled__2023-09-23T00:00:00+00:00', '--job-id', '284', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmpsa5qw_e7']
[2023-10-03T12:56:58.284+0000] {standard_task_runner.py:85} INFO - Job 284: Subtask preprocess_data
[2023-10-03T12:56:58.665+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.preprocess_data scheduled__2023-09-23T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T12:57:00.094+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-23T00:00:00+00:00'
[2023-10-03T12:57:00.283+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 75, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T12:57:00.348+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=preprocess_data, execution_date=20230923T000000, start_date=20231003T125657, end_date=20231003T125700
[2023-10-03T12:57:00.851+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 284 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 111)
[2023-10-03T12:57:01.193+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T12:57:01.438+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
