[2023-10-03T10:03:34.842+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [queued]>
[2023-10-03T10:03:35.045+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [queued]>
[2023-10-03T10:03:35.045+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:03:35.318+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-25 00:00:00+00:00
[2023-10-03T10:03:35.401+0000] {standard_task_runner.py:57} INFO - Started process 1661 to run task
[2023-10-03T10:03:35.470+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'preprocess_data', 'scheduled__2023-09-25T00:00:00+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmp9v5xcntz']
[2023-10-03T10:03:35.511+0000] {standard_task_runner.py:85} INFO - Job 142: Subtask preprocess_data
[2023-10-03T10:03:36.287+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T10:03:37.985+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-25T00:00:00+00:00'
[2023-10-03T10:03:38.236+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 63, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T10:03:38.356+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=preprocess_data, execution_date=20230925T000000, start_date=20231003T100334, end_date=20231003T100338
[2023-10-03T10:03:38.470+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 142 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 1661)
[2023-10-03T10:03:38.597+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:03:38.869+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T12:33:28.191+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [queued]>
[2023-10-03T12:33:28.499+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [queued]>
[2023-10-03T12:33:28.514+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T12:33:29.114+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-25 00:00:00+00:00
[2023-10-03T12:33:29.288+0000] {standard_task_runner.py:57} INFO - Started process 103 to run task
[2023-10-03T12:33:29.409+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'preprocess_data', 'scheduled__2023-09-25T00:00:00+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmpy93ut9pd']
[2023-10-03T12:33:29.493+0000] {standard_task_runner.py:85} INFO - Job 218: Subtask preprocess_data
[2023-10-03T12:33:30.487+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T12:33:31.988+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-25T00:00:00+00:00'
[2023-10-03T12:33:32.025+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 75, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T12:33:32.072+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=preprocess_data, execution_date=20230925T000000, start_date=20231003T123328, end_date=20231003T123332
[2023-10-03T12:33:32.358+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 218 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 103)
[2023-10-03T12:33:32.650+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T12:33:32.745+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T12:56:58.190+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [queued]>
[2023-10-03T12:56:58.288+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [queued]>
[2023-10-03T12:56:58.288+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T12:56:58.692+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-25 00:00:00+00:00
[2023-10-03T12:56:58.759+0000] {standard_task_runner.py:57} INFO - Started process 117 to run task
[2023-10-03T12:56:58.812+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'preprocess_data', 'scheduled__2023-09-25T00:00:00+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmp5w5n_yrh']
[2023-10-03T12:56:58.817+0000] {standard_task_runner.py:85} INFO - Job 292: Subtask preprocess_data
[2023-10-03T12:56:59.795+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T12:57:02.223+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-25T00:00:00+00:00'
[2023-10-03T12:57:02.612+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 75, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T12:57:02.959+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=preprocess_data, execution_date=20230925T000000, start_date=20231003T125658, end_date=20231003T125702
[2023-10-03T12:57:03.424+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 292 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 117)
[2023-10-03T12:57:03.723+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T12:57:03.993+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
