[2023-10-03T10:03:34.259+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-10-03T10:03:34.499+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-10-03T10:03:34.513+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:03:34.872+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-27 00:00:00+00:00
[2023-10-03T10:03:34.950+0000] {standard_task_runner.py:57} INFO - Started process 1653 to run task
[2023-10-03T10:03:34.981+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'preprocess_data', 'scheduled__2023-09-27T00:00:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmp95uj03sg']
[2023-10-03T10:03:35.005+0000] {standard_task_runner.py:85} INFO - Job 133: Subtask preprocess_data
[2023-10-03T10:03:35.585+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T10:03:37.172+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-27T00:00:00+00:00'
[2023-10-03T10:03:37.337+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 63, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T10:03:37.486+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=preprocess_data, execution_date=20230927T000000, start_date=20231003T100334, end_date=20231003T100337
[2023-10-03T10:03:37.705+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 133 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 1653)
[2023-10-03T10:03:37.896+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:03:38.091+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T12:33:28.146+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-10-03T12:33:28.445+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-10-03T12:33:28.471+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T12:33:29.158+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-27 00:00:00+00:00
[2023-10-03T12:33:29.455+0000] {standard_task_runner.py:57} INFO - Started process 108 to run task
[2023-10-03T12:33:29.576+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'preprocess_data', 'scheduled__2023-09-27T00:00:00+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmptifx_w3a']
[2023-10-03T12:33:29.578+0000] {standard_task_runner.py:85} INFO - Job 219: Subtask preprocess_data
[2023-10-03T12:33:30.648+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T12:33:32.860+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-27T00:00:00+00:00'
[2023-10-03T12:33:33.038+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 75, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T12:33:33.159+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=preprocess_data, execution_date=20230927T000000, start_date=20231003T123328, end_date=20231003T123333
[2023-10-03T12:33:33.403+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 219 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 108)
[2023-10-03T12:33:33.640+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T12:33:33.783+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T12:56:58.144+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-10-03T12:56:58.197+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-10-03T12:56:58.201+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T12:56:58.532+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-27 00:00:00+00:00
[2023-10-03T12:56:58.625+0000] {standard_task_runner.py:57} INFO - Started process 114 to run task
[2023-10-03T12:56:58.666+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'preprocess_data', 'scheduled__2023-09-27T00:00:00+00:00', '--job-id', '291', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmpkesvbz17']
[2023-10-03T12:56:58.688+0000] {standard_task_runner.py:85} INFO - Job 291: Subtask preprocess_data
[2023-10-03T12:56:59.598+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T12:57:01.680+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-27T00:00:00+00:00'
[2023-10-03T12:57:02.038+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 75, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T12:57:02.324+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=preprocess_data, execution_date=20230927T000000, start_date=20231003T125658, end_date=20231003T125702
[2023-10-03T12:57:03.043+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 291 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 114)
[2023-10-03T12:57:03.407+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T12:57:04.776+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
